import wordsListImg from "../assets/wordsListImages";

export const TEAM_NAMES = [
  "Minecraft Masters",
  "Pokémon Power",
  "Slime Squad",
  "Dino Defenders",
  "Emoji Experts",
  "Super Mario Stars",
  "Among Us All-Stars",
  "Lego Legends",
  "The Roblox Runners",
  "Fortnite Flyers",
  "The Avengers Crew",
  "The Snack Attackers",
  "Pikachu Pals",
  "The Zooming Zebras",
  "The LOL Llamas",
  "Minion Mayhem",
  "SpongeBob Squad",
  "Frozen Force",
  "The Pizza Party",
  "The Laughing Llamas",
  "The Super Squirrels",
  "Rainbow Ninjas",
  "The Giggle Squad",
  "The Flying Unicorns",
  "The Happy Hippos",
  "The Jellybean Jumpers",
  "The Silly Sprinkles",
  "The Thunder Tacos",
  "The Dancing Dragons",
];

export const WORDS_LIST = [
  {
    phrase: "Break the ice",
    img: wordsListImg["img1"],
    meaning: "To initiate conversation in a social setting.",
  },
  {
    phrase: "Head in the clouds",
    img: wordsListImg["img2"],
    meaning: "To be daydreaming or not paying attention.",
  },
  {
    phrase: "Butterflies in my stomach",
    img: wordsListImg["img3"],
    meaning: "To feel nervous or anxious.",
  },
  {
    phrase: "Piece of cake",
    img: wordsListImg["img4"],
    meaning: "Something very easy to do.",
  },
  {
    phrase: "Spill the beans",
    img: wordsListImg["img5"],
    meaning: "To reveal a secret.",
  },
  {
    phrase: "Hold your horses",
    img: wordsListImg["img6"],
    meaning: "To wait or be patient.",
  },
  { phrase: "Dancing dinosaur", img: wordsListImg["img7"], meaning: "" },
  { phrase: "Flying pizza", img: wordsListImg["img8"], meaning: "" },
  { phrase: "Jumping jellyfish", img: wordsListImg["img9"], meaning: "" },
  { phrase: "Running robot", img: wordsListImg["img10"], meaning: "" },
  { phrase: "Singing shark", img: wordsListImg["img11"], meaning: "" },
  { phrase: "Surfing squirrel", img: wordsListImg["img12"], meaning: "" },
  { phrase: "Skating penguin", img: wordsListImg["img13"], meaning: "" },
  // {
  //   phrase: "Cat out of the bag",
  //   img: wordsListImg["img14"],
  //   meaning: "The secret is revealed.",
  // },
  // {
  //   phrase: "On cloud nine",
  //   img: wordsListImg["img15"],
  //   meaning: "Extremely happy.",
  // },
  // {
  //   phrase: "Hit the road",
  //   img: wordsListImg["img16"],
  //   meaning: "To leave or start a journey.",
  // },
  // {
  //   phrase: "Take it easy",
  //   img: wordsListImg["img17"],
  //   meaning: "Relax or calm down.",
  // },
  // {
  //   phrase: "Keep your cool",
  //   img: wordsListImg["img18"],
  //   meaning: "Stay calm under pressure.",
  // },
  // {
  //   phrase: "Fish out of water",
  //   img: wordsListImg["img19"],
  //   meaning: "Uncomfortable in a new situation.",
  // },
  // {
  //   phrase: "Time flies",
  //   img: wordsListImg["img20"],
  //   meaning: "Time passes quickly.",
  // },
];
